import {requireAdmin,requireSameOrigin} from '../../../_lib/auth.js';
import {BASE_SELECT,normalizeMovie,slugify,cleanString,cleanBool,validHttpUrl} from '../../../_lib/db.js';
const allowedTypes=new Set(['movie','series']),allowedStatuses=new Set(['published','draft']);
function p(body){const year=body.year==null||body.year===''?null:Number.parseInt(body.year,10);return{title:cleanString(body.title,180),type:allowedTypes.has(body.type)?body.type:'movie',year:Number.isFinite(year)&&year>=1888&&year<=2100?year:null,language:cleanString(body.language,60),genre:cleanString(body.genre,180),quality:cleanString(body.quality,40),duration:cleanString(body.duration,40),imdb_rating:cleanString(body.imdb_rating,10),country:cleanString(body.country,80),director:cleanString(body.director,180),cast:cleanString(body.cast,300),release_date:body.release_date?cleanString(body.release_date,10):null,description:cleanString(body.description,5000),poster_url:validHttpUrl(body.poster_url)||'',download_url_1:validHttpUrl(body.download_url_1)||'',download_url_2:validHttpUrl(body.download_url_2)||'',download_url_3:validHttpUrl(body.download_url_3)||'',is_featured:cleanBool(body.is_featured)?1:0,is_pinned:cleanBool(body.is_pinned)?1:0,status:allowedStatuses.has(body.status)?body.status:'draft',category_slugs:Array.isArray(body.category_slugs)?body.category_slugs.map(x=>slugify(x)).filter(Boolean).slice(0,20):[]}}
async function slug(db,base,id){let s=base||'untitled';for(let i=0;i<30;i++){const x=i?s+'-'+i:s;const q=await db.prepare('SELECT id FROM movies WHERE slug=? AND id<>?').bind(x,id).first();if(!q)return x;}return `${s}-${crypto.randomUUID().slice(0,8)}`}
async function cats(db,id,slugs){await db.prepare('DELETE FROM movie_categories WHERE movie_id=?').bind(id).run();for(const s of slugs){const c=await db.prepare('SELECT id FROM categories WHERE slug=?').bind(s).first();if(c)await db.prepare('INSERT OR IGNORE INTO movie_categories(movie_id,category_id) VALUES(?,?)').bind(id,c.id).run();}}
async function item(db,id){const row=await db.prepare(`${BASE_SELECT} WHERE m.id=? GROUP BY m.id`).bind(id).first();return normalizeMovie(row)}
export async function onRequestPut({request,env,params}){const o=requireSameOrigin(request);if(o)return o;const a=await requireAdmin(request,env);if(a)return a;if(!env.DB)return Response.json({error:'D1 database is not connected.'},{status:503});const id=Number.parseInt(params.id,10);if(!Number.isFinite(id))return Response.json({error:'Invalid id'},{status:400});let body;try{body=await request.json()}catch{return Response.json({error:'Invalid JSON'},{status:400})}const x=p(body);if(!x.title)return Response.json({error:'Title is required.'},{status:400});const s=await slug(env.DB,slugify(x.title),id);const old=await env.DB.prepare('SELECT poster_url FROM movies WHERE id=?').bind(id).first();const r=await env.DB.prepare(`UPDATE movies SET title=?,slug=?,type=?,description=?,poster_url=?,year=?,language=?,genre=?,quality=?,duration=?,imdb_rating=?,country=?,cast=?,director=?,release_date=?,is_featured=?,is_pinned=?,status=?,download_url_1=?,download_url_2=?,download_url_3=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(x.title,s,x.type,x.description,x.poster_url||old?.poster_url||'',x.year,x.language,x.genre,x.quality,x.duration,x.imdb_rating,x.country,x.cast,x.director,x.release_date,x.is_featured,x.is_pinned,x.status,x.download_url_1,x.download_url_2,x.download_url_3,id).run();if(!r.success)return Response.json({error:'Update failed.'},{status:400});await cats(env.DB,id,x.category_slugs);return Response.json({item:await item(env.DB,id)})}
export async function onRequestDelete({request,env,params}){const o=requireSameOrigin(request);if(o)return o;const a=await requireAdmin(request,env);if(a)return a;if(!env.DB)return Response.json({error:'D1 database is not connected.'},{status:503});const id=Number.parseInt(params.id,10);if(!Number.isFinite(id))return Response.json({error:'Invalid id'},{status:400});const r=await env.DB.prepare('DELETE FROM movies WHERE id=?').bind(id).run();if(!r.success||!r.meta.changes)return Response.json({error:'Title not found.'},{status:404});return Response.json({ok:true})}
